export const RECEIVE_ALLCARDS = "RECEIVE_ALLCARDS";
export const UPDATE_ASSIGNMENT = "UPDATE_ASSIGNMENT";
export const UNSAVED_CHANGES = "UNSAVED_CHANGES";
export const UPDATE_UNSAVED_ASSN = "UPDATE_UNSAVED_ASSN";
export const ADD_DATECARD = "ADD_DATECARD";
