export const RECEIVE_ALLCARDS = "RECEIVE_ALLCARDS";
export const UPDATE_ASSIGNEE = "UPDATE_ASSIGNEE";
export const UNSAVED_CHANGES = "UNSAVED_CHANGES";
export const UPDATE_UNSAVED_ASSN = "UPDATE_UNSAVED_ASSN";
export const ADD_DATECARD = "ADD_DATECARD";
export const ADD_ASSIGNEE = "ADD_ASSIGNEE";
export const MARK_UNSAVED = "MARK_UNSAVED";
